In [1]:
import pandas as pd

In [4]:
# From https://stackoverflow.com/questions/60154404/is-there-the-equivalent-of-to-markdown-to-read-data
df = pd.read_table("fingering-key-c.md", sep="|", header=0, index_col=1, skipinitialspace=True).dropna(axis=1, how='all').iloc[1:] 
df

,C,C#,D,Eb,F,F#,G,G#,A,Bb,...,F .1,F#.1,G .1,G#.1,A .1,Bb.1,B .1,C .2,C#.2,D .2
Key of C,,,,,,,,,,,,,,,,,,,,,
Value:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2^7 (128),x,x,x,x,x,x,x,x,x,x,...,/,/,/,/,/,/,/,/,/,/
2^6 (64),x,x,x,x,x,x,x,x,x,x,...,x,x,x,x,x,x,x,x,x,x
2^5 (32),x,x,x,x,x,x,x,x,x,o,...,x,x,x,x,x,x,x,o,o,o
2^4 (16),x,x,x,x,x,x,x,o,o,x,...,x,x,x,o,o,o,o,o,x,x
2^3 (8),x,x,x,x,x,o,o,x,o,x,...,x,o,o,x,o,o,x,x,x,x
2^2 (4),x,x,x,x,o,x,o,x,o,o,...,o,x,o,o,o,x,x,x,o,o
2^1 (2),x,x,/,o,x,/,o,/,o,o,...,x,o,o,o,o,x,o,o,x,x
2^0 (1),x,/,o,o,o,x,o,o,o,o,...,o,o,o,o,o,/,o,o,x',/

In [23]:
def  table_to_value(col):
    key_val = 0
    for ii, v in enumerate(col[1:].values):
        if v.strip().lower() == "x":
            key_val += 2**(7-ii)
    return key_val

In [25]:
for name, col in df.iteritems():
    col[0] = table_to_value(col)

In [27]:
print(df.to_markdown())

| Key of C     | C    | C#   | D    | Eb   | F    | F#   | G    | G#   | A    | Bb   | B    | C .1   | C#.1   | D .1   | Eb.1   | E    | F .1   | F#.1   | G .1   | G#.1   | A .1   | Bb.1   | B .1   | C .2   | C#.2   | D .2   |
|:-------------|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-------|:-------|:-------|:-------|:-----|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|
| Value:       | 255  | 254  | 252  | 252  | 250  | 245  | 240  | 236  | 224  | 216  | 192  | 160    | 96     | 32     | 62     | 124  | 122    | 116    | 112    | 104    | 96     | 102    | 108    | 76     | 90     | 90     |
| 2^7 (128)    | x    | x    | x    | x    | x    | x    | x    | x    | x    | x    | x    | x      | o      | o      | o      | /    | /      | /      | /      | /      | /      | /      | /      | /      | /      | /      |
| 2^6 (64)     | x    | x    | x    | x    | x    | x    | x    | x    | x    | x    | x    | o      | x      | o      | o      | x    | x      | x      | x      | x      | x      | x      | x      | x      | x      | x      |
| 2^5 (32)     | x    | x    | x    | x    | x    | x    | x    | x    | x    | o    | o    | x      | x      | x      | x      | x    | x      | x      | x      | x      | x      | x      | x      | o      | o      | o      |
| 2^4 (16)     | x    | x    | x    | x    | x    | x    | x    | o    | o    | x    | o    | o      | o      | o      | x      | x    | x      | x      | x      | o      | o      | o      | o      | o      | x      | x      |
| 2^3 (8)      | x    | x    | x    | x    | x    | o    | o    | x    | o    | x    | o    | o      | o      | o      | x      | x    | x      | o      | o      | x      | o      | o      | x      | x      | x      | x      |
| 2^2 (4)      | x    | x    | x    | x    | o    | x    | o    | x    | o    | o    | o    | o      | o      | o      | x      | x    | o      | x      | o      | o      | o      | x      | x      | x      | o      | o      |
| 2^1 (2)      | x    | x    | /    | o    | x    | /    | o    | /    | o    | o    | o    | o      | o      | o      | x      | o    | x      | o      | o      | o      | o      | x      | o      | o      | x      | x      |
| 2^0 (1)      | x    | /    | o    | o    | o    | x    | o    | o    | o    | o    | o    | o      | o      | o      | o      | o    | o      | o      | o      | o      | o      | /      | o      | o      | x'     | /      |